on:
  workflow_dispatch:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install-keys
        run: |
           curl -fsSL https://archive.raspberrypi.com/debian/raspberrypi.gpg.key \
             | gpg --dearmor | sudo tee /usr/share/keyrings/raspberrypi-archive-keyring.gpg

      - name: install-deps
        run: |
          sudo ./install_deps.sh

      - name: build
        run: |
          ./build.sh
