on:
  workflow_dispatch:
  pull_request:

env:
  BUILD_PROFILE: custom

jobs:
  build-docker:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/asssaf/rpi-image-gen
          tags: type=raw,value=latest,priority=2000

      - name: Build and push builder image
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: checkout
        uses: actions/checkout@v3

      - name: cache-build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: "${{github.workspace}}/artifacts"
          key: "build-${{env.BUILD_PROFILE}}-${{ hashFiles(format('{0}/**', env.BUILD_PROFILE)) }}"

      - name: run build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          docker run \
            --name builder \
            --privileged \
            -v "${GITHUB_WORKSPACE}/${BUILD_PROFILE}:/${BUILD_PROFILE}" \
            ghcr.io/asssaf/rpi-image-gen \
            -D /${BUILD_PROFILE}/ -c ${BUILD_PROFILE} -o /${BUILD_PROFILE}/${BUILD_PROFILE}.options

          mkdir "${{github.workspace}}/artifacts"
          docker cp builder:/rpi-image-gen/work/${BUILD_PROFILE}/deploy/${BUILD_PROFILE}.img "${GITHUB_WORKSPACE}/artifacts/"
          docker cp builder:/rpi-image-gen/work/${BUILD_PROFILE}/deploy/${BUILD_PROFILE}.sbom "${GITHUB_WORKSPACE}/artifacts/"

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: "${{github.workspace}}/artifacts/${{env.BUILD_PROFILE}}.img"

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: "${{github.workspace}}/artifacts/${{env.BUILD_PROFILE}}.sbom"


  test:
    env:
      KERNEL_VERSION: 6.12.34
    runs-on: ubuntu-24.04-arm
    needs: [build-docker]
    steps:
      - name: install-qemu
        run: |
          sudo apt install -y qemu-system-arm

      - name: download-kernel
        uses: actions/download-artifact@v4
        with:
          name: kernel8-qemu
          path: "${{github.workspace}}"

      - name: download-image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: "${{github.workspace}}"

      - name: run
        timeout-minutes: 5
        run: |
          set -euxo pipefail

          docker create --name rpi-kernel --platform linux/arm64/v8 ghcr.io/asssaf/rpi-kernel:${{ env.KERNEL_VERSION }}-default true
          docker cp rpi-kernel:/Image-${{ env.KERNEL_VERSION }} "${GITHUB_WORKSPACE}/Image"

          KERNEL="${GITHUB_WORKSPACE}/Image"
          IMAGE="${GITHUB_WORKSPACE}/${BUILD_PROFILE}.img"
          qemu-system-aarch64 -machine virt -cpu cortex-a72 -smp 2 -m 1G \
            -kernel "$KERNEL" -append "root=/dev/vda2 rootfstype=ext4 rw console=ttyAMA0 debug=y" \
            -nographic \
            -drive format=raw,file=$IMAGE,if=none,id=hd0,cache=writeback,media=disk \
            -device virtio-blk,drive=hd0,bootindex=0 \
            -netdev user,id=mynet,hostfwd=tcp::2223-:22 \
            -device virtio-net-pci,netdev=mynet \
            -monitor telnet:127.0.0.1:5555,server,nowait > qemu.out &

          until sshpass -p raspberry ssh -o StrictHostKeychecking=no -p 2223 user@127.0.0.1 sudo shutdown -h now
          do
            sleep 5
          done

