on:
  workflow_dispatch:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install-deps
        run: |
          sudo ./install_deps.sh

      - name: build
        run: |
          ./build.sh
